namespace JsonBench.Models.Isolation;

public class Node100<T>
{
    public T key_0 { get; set; }
    public T key_1 { get; set; }
    public T key_2 { get; set; }
    public T key_3 { get; set; }
    public T key_4 { get; set; }
    public T key_5 { get; set; }
    public T key_6 { get; set; }
    public T key_7 { get; set; }
    public T key_8 { get; set; }
    public T key_9 { get; set; }
    public T key_10 { get; set; }
    public T key_11 { get; set; }
    public T key_12 { get; set; }
    public T key_13 { get; set; }
    public T key_14 { get; set; }
    public T key_15 { get; set; }
    public T key_16 { get; set; }
    public T key_17 { get; set; }
    public T key_18 { get; set; }
    public T key_19 { get; set; }
    public T key_20 { get; set; }
    public T key_21 { get; set; }
    public T key_22 { get; set; }
    public T key_23 { get; set; }
    public T key_24 { get; set; }
    public T key_25 { get; set; }
    public T key_26 { get; set; }
    public T key_27 { get; set; }
    public T key_28 { get; set; }
    public T key_29 { get; set; }
    public T key_30 { get; set; }
    public T key_31 { get; set; }
    public T key_32 { get; set; }
    public T key_33 { get; set; }
    public T key_34 { get; set; }
    public T key_35 { get; set; }
    public T key_36 { get; set; }
    public T key_37 { get; set; }
    public T key_38 { get; set; }
    public T key_39 { get; set; }
    public T key_40 { get; set; }
    public T key_41 { get; set; }
    public T key_42 { get; set; }
    public T key_43 { get; set; }
    public T key_44 { get; set; }
    public T key_45 { get; set; }
    public T key_46 { get; set; }
    public T key_47 { get; set; }
    public T key_48 { get; set; }
    public T key_49 { get; set; }
    public T key_50 { get; set; }
    public T key_51 { get; set; }
    public T key_52 { get; set; }
    public T key_53 { get; set; }
    public T key_54 { get; set; }
    public T key_55 { get; set; }
    public T key_56 { get; set; }
    public T key_57 { get; set; }
    public T key_58 { get; set; }
    public T key_59 { get; set; }
    public T key_60 { get; set; }
    public T key_61 { get; set; }
    public T key_62 { get; set; }
    public T key_63 { get; set; }
    public T key_64 { get; set; }
    public T key_65 { get; set; }
    public T key_66 { get; set; }
    public T key_67 { get; set; }
    public T key_68 { get; set; }
    public T key_69 { get; set; }
    public T key_70 { get; set; }
    public T key_71 { get; set; }
    public T key_72 { get; set; }
    public T key_73 { get; set; }
    public T key_74 { get; set; }
    public T key_75 { get; set; }
    public T key_76 { get; set; }
    public T key_77 { get; set; }
    public T key_78 { get; set; }
    public T key_79 { get; set; }
    public T key_80 { get; set; }
    public T key_81 { get; set; }
    public T key_82 { get; set; }
    public T key_83 { get; set; }
    public T key_84 { get; set; }
    public T key_85 { get; set; }
    public T key_86 { get; set; }
    public T key_87 { get; set; }
    public T key_88 { get; set; }
    public T key_89 { get; set; }
    public T key_90 { get; set; }
    public T key_91 { get; set; }
    public T key_92 { get; set; }
    public T key_93 { get; set; }
    public T key_94 { get; set; }
    public T key_95 { get; set; }
    public T key_96 { get; set; }
    public T key_97 { get; set; }
    public T key_98 { get; set; }
    public Node100<T>? key_99 { get; set; }
}
