namespace JsonBench.Models.Isolation;

public class Node200<T>
{
    public T key_0 { get; set; }
    public T key_1 { get; set; }
    public T key_2 { get; set; }
    public T key_3 { get; set; }
    public T key_4 { get; set; }
    public T key_5 { get; set; }
    public T key_6 { get; set; }
    public T key_7 { get; set; }
    public T key_8 { get; set; }
    public T key_9 { get; set; }
    public T key_10 { get; set; }
    public T key_11 { get; set; }
    public T key_12 { get; set; }
    public T key_13 { get; set; }
    public T key_14 { get; set; }
    public T key_15 { get; set; }
    public T key_16 { get; set; }
    public T key_17 { get; set; }
    public T key_18 { get; set; }
    public T key_19 { get; set; }
    public T key_20 { get; set; }
    public T key_21 { get; set; }
    public T key_22 { get; set; }
    public T key_23 { get; set; }
    public T key_24 { get; set; }
    public T key_25 { get; set; }
    public T key_26 { get; set; }
    public T key_27 { get; set; }
    public T key_28 { get; set; }
    public T key_29 { get; set; }
    public T key_30 { get; set; }
    public T key_31 { get; set; }
    public T key_32 { get; set; }
    public T key_33 { get; set; }
    public T key_34 { get; set; }
    public T key_35 { get; set; }
    public T key_36 { get; set; }
    public T key_37 { get; set; }
    public T key_38 { get; set; }
    public T key_39 { get; set; }
    public T key_40 { get; set; }
    public T key_41 { get; set; }
    public T key_42 { get; set; }
    public T key_43 { get; set; }
    public T key_44 { get; set; }
    public T key_45 { get; set; }
    public T key_46 { get; set; }
    public T key_47 { get; set; }
    public T key_48 { get; set; }
    public T key_49 { get; set; }
    public T key_50 { get; set; }
    public T key_51 { get; set; }
    public T key_52 { get; set; }
    public T key_53 { get; set; }
    public T key_54 { get; set; }
    public T key_55 { get; set; }
    public T key_56 { get; set; }
    public T key_57 { get; set; }
    public T key_58 { get; set; }
    public T key_59 { get; set; }
    public T key_60 { get; set; }
    public T key_61 { get; set; }
    public T key_62 { get; set; }
    public T key_63 { get; set; }
    public T key_64 { get; set; }
    public T key_65 { get; set; }
    public T key_66 { get; set; }
    public T key_67 { get; set; }
    public T key_68 { get; set; }
    public T key_69 { get; set; }
    public T key_70 { get; set; }
    public T key_71 { get; set; }
    public T key_72 { get; set; }
    public T key_73 { get; set; }
    public T key_74 { get; set; }
    public T key_75 { get; set; }
    public T key_76 { get; set; }
    public T key_77 { get; set; }
    public T key_78 { get; set; }
    public T key_79 { get; set; }
    public T key_80 { get; set; }
    public T key_81 { get; set; }
    public T key_82 { get; set; }
    public T key_83 { get; set; }
    public T key_84 { get; set; }
    public T key_85 { get; set; }
    public T key_86 { get; set; }
    public T key_87 { get; set; }
    public T key_88 { get; set; }
    public T key_89 { get; set; }
    public T key_90 { get; set; }
    public T key_91 { get; set; }
    public T key_92 { get; set; }
    public T key_93 { get; set; }
    public T key_94 { get; set; }
    public T key_95 { get; set; }
    public T key_96 { get; set; }
    public T key_97 { get; set; }
    public T key_98 { get; set; }
    public T key_99 { get; set; }
    public T key_100 { get; set; }
    public T key_101 { get; set; }
    public T key_102 { get; set; }
    public T key_103 { get; set; }
    public T key_104 { get; set; }
    public T key_105 { get; set; }
    public T key_106 { get; set; }
    public T key_107 { get; set; }
    public T key_108 { get; set; }
    public T key_109 { get; set; }
    public T key_110 { get; set; }
    public T key_111 { get; set; }
    public T key_112 { get; set; }
    public T key_113 { get; set; }
    public T key_114 { get; set; }
    public T key_115 { get; set; }
    public T key_116 { get; set; }
    public T key_117 { get; set; }
    public T key_118 { get; set; }
    public T key_119 { get; set; }
    public T key_120 { get; set; }
    public T key_121 { get; set; }
    public T key_122 { get; set; }
    public T key_123 { get; set; }
    public T key_124 { get; set; }
    public T key_125 { get; set; }
    public T key_126 { get; set; }
    public T key_127 { get; set; }
    public T key_128 { get; set; }
    public T key_129 { get; set; }
    public T key_130 { get; set; }
    public T key_131 { get; set; }
    public T key_132 { get; set; }
    public T key_133 { get; set; }
    public T key_134 { get; set; }
    public T key_135 { get; set; }
    public T key_136 { get; set; }
    public T key_137 { get; set; }
    public T key_138 { get; set; }
    public T key_139 { get; set; }
    public T key_140 { get; set; }
    public T key_141 { get; set; }
    public T key_142 { get; set; }
    public T key_143 { get; set; }
    public T key_144 { get; set; }
    public T key_145 { get; set; }
    public T key_146 { get; set; }
    public T key_147 { get; set; }
    public T key_148 { get; set; }
    public T key_149 { get; set; }
    public T key_150 { get; set; }
    public T key_151 { get; set; }
    public T key_152 { get; set; }
    public T key_153 { get; set; }
    public T key_154 { get; set; }
    public T key_155 { get; set; }
    public T key_156 { get; set; }
    public T key_157 { get; set; }
    public T key_158 { get; set; }
    public T key_159 { get; set; }
    public T key_160 { get; set; }
    public T key_161 { get; set; }
    public T key_162 { get; set; }
    public T key_163 { get; set; }
    public T key_164 { get; set; }
    public T key_165 { get; set; }
    public T key_166 { get; set; }
    public T key_167 { get; set; }
    public T key_168 { get; set; }
    public T key_169 { get; set; }
    public T key_170 { get; set; }
    public T key_171 { get; set; }
    public T key_172 { get; set; }
    public T key_173 { get; set; }
    public T key_174 { get; set; }
    public T key_175 { get; set; }
    public T key_176 { get; set; }
    public T key_177 { get; set; }
    public T key_178 { get; set; }
    public T key_179 { get; set; }
    public T key_180 { get; set; }
    public T key_181 { get; set; }
    public T key_182 { get; set; }
    public T key_183 { get; set; }
    public T key_184 { get; set; }
    public T key_185 { get; set; }
    public T key_186 { get; set; }
    public T key_187 { get; set; }
    public T key_188 { get; set; }
    public T key_189 { get; set; }
    public T key_190 { get; set; }
    public T key_191 { get; set; }
    public T key_192 { get; set; }
    public T key_193 { get; set; }
    public T key_194 { get; set; }
    public T key_195 { get; set; }
    public T key_196 { get; set; }
    public T key_197 { get; set; }
    public T key_198 { get; set; }
    public Node200<T>? key_199 { get; set; }
}
