namespace JsonBench.Models.MinimalFactorial;

public class D10_W100_B
{
    public bool key_0 { get; set; }
    public bool key_1 { get; set; }
    public bool key_2 { get; set; }
    public bool key_3 { get; set; }
    public bool key_4 { get; set; }
    public bool key_5 { get; set; }
    public bool key_6 { get; set; }
    public bool key_7 { get; set; }
    public bool key_8 { get; set; }
    public bool key_9 { get; set; }
    public bool key_10 { get; set; }
    public bool key_11 { get; set; }
    public bool key_12 { get; set; }
    public bool key_13 { get; set; }
    public bool key_14 { get; set; }
    public bool key_15 { get; set; }
    public bool key_16 { get; set; }
    public bool key_17 { get; set; }
    public bool key_18 { get; set; }
    public bool key_19 { get; set; }
    public bool key_20 { get; set; }
    public bool key_21 { get; set; }
    public bool key_22 { get; set; }
    public bool key_23 { get; set; }
    public bool key_24 { get; set; }
    public bool key_25 { get; set; }
    public bool key_26 { get; set; }
    public bool key_27 { get; set; }
    public bool key_28 { get; set; }
    public bool key_29 { get; set; }
    public bool key_30 { get; set; }
    public bool key_31 { get; set; }
    public bool key_32 { get; set; }
    public bool key_33 { get; set; }
    public bool key_34 { get; set; }
    public bool key_35 { get; set; }
    public bool key_36 { get; set; }
    public bool key_37 { get; set; }
    public bool key_38 { get; set; }
    public bool key_39 { get; set; }
    public bool key_40 { get; set; }
    public bool key_41 { get; set; }
    public bool key_42 { get; set; }
    public bool key_43 { get; set; }
    public bool key_44 { get; set; }
    public bool key_45 { get; set; }
    public bool key_46 { get; set; }
    public bool key_47 { get; set; }
    public bool key_48 { get; set; }
    public bool key_49 { get; set; }
    public bool key_50 { get; set; }
    public bool key_51 { get; set; }
    public bool key_52 { get; set; }
    public bool key_53 { get; set; }
    public bool key_54 { get; set; }
    public bool key_55 { get; set; }
    public bool key_56 { get; set; }
    public bool key_57 { get; set; }
    public bool key_58 { get; set; }
    public bool key_59 { get; set; }
    public bool key_60 { get; set; }
    public bool key_61 { get; set; }
    public bool key_62 { get; set; }
    public bool key_63 { get; set; }
    public bool key_64 { get; set; }
    public bool key_65 { get; set; }
    public bool key_66 { get; set; }
    public bool key_67 { get; set; }
    public bool key_68 { get; set; }
    public bool key_69 { get; set; }
    public bool key_70 { get; set; }
    public bool key_71 { get; set; }
    public bool key_72 { get; set; }
    public bool key_73 { get; set; }
    public bool key_74 { get; set; }
    public bool key_75 { get; set; }
    public bool key_76 { get; set; }
    public bool key_77 { get; set; }
    public bool key_78 { get; set; }
    public bool key_79 { get; set; }
    public bool key_80 { get; set; }
    public bool key_81 { get; set; }
    public bool key_82 { get; set; }
    public bool key_83 { get; set; }
    public bool key_84 { get; set; }
    public bool key_85 { get; set; }
    public bool key_86 { get; set; }
    public bool key_87 { get; set; }
    public bool key_88 { get; set; }
    public bool key_89 { get; set; }
    public bool key_90 { get; set; }
    public bool key_91 { get; set; }
    public bool key_92 { get; set; }
    public bool key_93 { get; set; }
    public bool key_94 { get; set; }
    public bool key_95 { get; set; }
    public bool key_96 { get; set; }
    public bool key_97 { get; set; }
    public bool key_98 { get; set; }
    public D10_W100_B? key_99 { get; set; }
}
