namespace JsonBench.Models.MinimalFactorial;

public class D10_W100_T
{
    public string key_0 { get; set; }
    public string key_1 { get; set; }
    public string key_2 { get; set; }
    public string key_3 { get; set; }
    public string key_4 { get; set; }
    public string key_5 { get; set; }
    public string key_6 { get; set; }
    public string key_7 { get; set; }
    public string key_8 { get; set; }
    public string key_9 { get; set; }
    public string key_10 { get; set; }
    public string key_11 { get; set; }
    public string key_12 { get; set; }
    public string key_13 { get; set; }
    public string key_14 { get; set; }
    public string key_15 { get; set; }
    public string key_16 { get; set; }
    public string key_17 { get; set; }
    public string key_18 { get; set; }
    public string key_19 { get; set; }
    public string key_20 { get; set; }
    public string key_21 { get; set; }
    public string key_22 { get; set; }
    public string key_23 { get; set; }
    public string key_24 { get; set; }
    public string key_25 { get; set; }
    public string key_26 { get; set; }
    public string key_27 { get; set; }
    public string key_28 { get; set; }
    public string key_29 { get; set; }
    public string key_30 { get; set; }
    public string key_31 { get; set; }
    public string key_32 { get; set; }
    public string key_33 { get; set; }
    public string key_34 { get; set; }
    public string key_35 { get; set; }
    public string key_36 { get; set; }
    public string key_37 { get; set; }
    public string key_38 { get; set; }
    public string key_39 { get; set; }
    public string key_40 { get; set; }
    public string key_41 { get; set; }
    public string key_42 { get; set; }
    public string key_43 { get; set; }
    public string key_44 { get; set; }
    public string key_45 { get; set; }
    public string key_46 { get; set; }
    public string key_47 { get; set; }
    public string key_48 { get; set; }
    public string key_49 { get; set; }
    public string key_50 { get; set; }
    public string key_51 { get; set; }
    public string key_52 { get; set; }
    public string key_53 { get; set; }
    public string key_54 { get; set; }
    public string key_55 { get; set; }
    public string key_56 { get; set; }
    public string key_57 { get; set; }
    public string key_58 { get; set; }
    public string key_59 { get; set; }
    public string key_60 { get; set; }
    public string key_61 { get; set; }
    public string key_62 { get; set; }
    public string key_63 { get; set; }
    public string key_64 { get; set; }
    public string key_65 { get; set; }
    public string key_66 { get; set; }
    public string key_67 { get; set; }
    public string key_68 { get; set; }
    public string key_69 { get; set; }
    public string key_70 { get; set; }
    public string key_71 { get; set; }
    public string key_72 { get; set; }
    public string key_73 { get; set; }
    public string key_74 { get; set; }
    public string key_75 { get; set; }
    public string key_76 { get; set; }
    public string key_77 { get; set; }
    public string key_78 { get; set; }
    public string key_79 { get; set; }
    public string key_80 { get; set; }
    public string key_81 { get; set; }
    public string key_82 { get; set; }
    public string key_83 { get; set; }
    public string key_84 { get; set; }
    public string key_85 { get; set; }
    public string key_86 { get; set; }
    public string key_87 { get; set; }
    public string key_88 { get; set; }
    public string key_89 { get; set; }
    public string key_90 { get; set; }
    public string key_91 { get; set; }
    public string key_92 { get; set; }
    public string key_93 { get; set; }
    public string key_94 { get; set; }
    public string key_95 { get; set; }
    public string key_96 { get; set; }
    public string key_97 { get; set; }
    public string key_98 { get; set; }
    public D10_W100_T? key_99 { get; set; }
}
