namespace JsonBench.Models.MinimalFactorial;

public class D2_W100_N
{
    public int key_0 { get; set; }
    public int key_1 { get; set; }
    public int key_2 { get; set; }
    public int key_3 { get; set; }
    public int key_4 { get; set; }
    public int key_5 { get; set; }
    public int key_6 { get; set; }
    public int key_7 { get; set; }
    public int key_8 { get; set; }
    public int key_9 { get; set; }
    public int key_10 { get; set; }
    public int key_11 { get; set; }
    public int key_12 { get; set; }
    public int key_13 { get; set; }
    public int key_14 { get; set; }
    public int key_15 { get; set; }
    public int key_16 { get; set; }
    public int key_17 { get; set; }
    public int key_18 { get; set; }
    public int key_19 { get; set; }
    public int key_20 { get; set; }
    public int key_21 { get; set; }
    public int key_22 { get; set; }
    public int key_23 { get; set; }
    public int key_24 { get; set; }
    public int key_25 { get; set; }
    public int key_26 { get; set; }
    public int key_27 { get; set; }
    public int key_28 { get; set; }
    public int key_29 { get; set; }
    public int key_30 { get; set; }
    public int key_31 { get; set; }
    public int key_32 { get; set; }
    public int key_33 { get; set; }
    public int key_34 { get; set; }
    public int key_35 { get; set; }
    public int key_36 { get; set; }
    public int key_37 { get; set; }
    public int key_38 { get; set; }
    public int key_39 { get; set; }
    public int key_40 { get; set; }
    public int key_41 { get; set; }
    public int key_42 { get; set; }
    public int key_43 { get; set; }
    public int key_44 { get; set; }
    public int key_45 { get; set; }
    public int key_46 { get; set; }
    public int key_47 { get; set; }
    public int key_48 { get; set; }
    public int key_49 { get; set; }
    public int key_50 { get; set; }
    public int key_51 { get; set; }
    public int key_52 { get; set; }
    public int key_53 { get; set; }
    public int key_54 { get; set; }
    public int key_55 { get; set; }
    public int key_56 { get; set; }
    public int key_57 { get; set; }
    public int key_58 { get; set; }
    public int key_59 { get; set; }
    public int key_60 { get; set; }
    public int key_61 { get; set; }
    public int key_62 { get; set; }
    public int key_63 { get; set; }
    public int key_64 { get; set; }
    public int key_65 { get; set; }
    public int key_66 { get; set; }
    public int key_67 { get; set; }
    public int key_68 { get; set; }
    public int key_69 { get; set; }
    public int key_70 { get; set; }
    public int key_71 { get; set; }
    public int key_72 { get; set; }
    public int key_73 { get; set; }
    public int key_74 { get; set; }
    public int key_75 { get; set; }
    public int key_76 { get; set; }
    public int key_77 { get; set; }
    public int key_78 { get; set; }
    public int key_79 { get; set; }
    public int key_80 { get; set; }
    public int key_81 { get; set; }
    public int key_82 { get; set; }
    public int key_83 { get; set; }
    public int key_84 { get; set; }
    public int key_85 { get; set; }
    public int key_86 { get; set; }
    public int key_87 { get; set; }
    public int key_88 { get; set; }
    public int key_89 { get; set; }
    public int key_90 { get; set; }
    public int key_91 { get; set; }
    public int key_92 { get; set; }
    public int key_93 { get; set; }
    public int key_94 { get; set; }
    public int key_95 { get; set; }
    public int key_96 { get; set; }
    public int key_97 { get; set; }
    public int key_98 { get; set; }
    public D2_W100_N? key_99 { get; set; }
}
